/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/abrechnungen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_11"];
        put?: never;
        post: operations["create_11"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/abrechnungen/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_8"];
        post?: never;
        delete: operations["delete_8"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/allgemeinausgaben": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_10"];
        put?: never;
        post: operations["create_10"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/allgemeinausgaben/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_7"];
        post?: never;
        delete: operations["delete_7"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benutzer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_9"];
        put?: never;
        post: operations["create_9"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benutzer/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_11"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benutzer/{id}/passwort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["passwortSetzen"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/einladungen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_8"];
        put?: never;
        post: operations["create_8"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/einladungen/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_6"];
        post?: never;
        delete: operations["delete_6"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_7"];
        put?: never;
        post: operations["create_7"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_5"];
        post?: never;
        delete: operations["delete_5"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/konsumationen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_6"];
        put?: never;
        post: operations["create_6"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/konsumationen/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_4"];
        post?: never;
        delete: operations["delete_4"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/konsumationsangebote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_5"];
        put?: never;
        post: operations["create_5"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/konsumationsangebote/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_3"];
        post?: never;
        delete: operations["delete_3"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mahnungen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_4"];
        put?: never;
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mahnungen/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_10"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parteien": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_3"];
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parteien/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_2"];
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_2"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_1"];
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teilnahmen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll_1"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teilnahmen/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teilnahmen/meine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findMeine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zahlungen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["findAll"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zahlungen/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_9"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AbrechnungKurz: {
            /** Format: int64 */
            id: number;
        };
        AbrechnungRequest: {
            anteilAllgemeinkosten: number;
            /** Format: int64 */
            teilnahmeId: number;
            totalBetrag: number;
            totalKonsumation: number;
            /** Format: date */
            zustellungsDatum?: string;
            zustellungskanal: components["schemas"]["Zustellungskanal"];
        };
        AbrechnungResponse: {
            anteilAllgemeinkosten: number;
            /** Format: int64 */
            id: number;
            teilnahme: components["schemas"]["TeilnahmeKurz"];
            totalBetrag: number;
            totalKonsumation: number;
            /** Format: date */
            zustellungsDatum?: string;
            zustellungskanal: components["schemas"]["Zustellungskanal"];
        };
        AbrechnungUpdateRequest: {
            anteilAllgemeinkosten: number;
            totalBetrag: number;
            totalKonsumation: number;
            /** Format: date */
            zustellungsDatum?: string;
            zustellungskanal: components["schemas"]["Zustellungskanal"];
        };
        AllgemeinausgabeRequest: {
            beschreibung: string;
            betrag: number;
            /** Format: int64 */
            eventId: number;
            herkunft?: string;
        };
        AllgemeinausgabeResponse: {
            beschreibung: string;
            betrag: number;
            event: components["schemas"]["EventResponse"];
            herkunft?: string;
            /** Format: int64 */
            id: number;
        };
        ApiError: {
            message: string;
            /** Format: int32 */
            status: number;
        };
        BenutzerRequest: {
            email: string;
            /** Format: int64 */
            parteiId?: number;
            passwort: string;
            rolle: components["schemas"]["Rolle"];
        };
        BenutzerResponse: {
            email: string;
            /** Format: int64 */
            id: number;
            partei?: components["schemas"]["ParteiKurz"];
            rolle: components["schemas"]["Rolle"];
        };
        /** @enum {string} */
        BuffetBeitrag: "KEINER" | "SALAT" | "BROT_ZOPF" | "DESSERT" | "WEITERE";
        EinladungKurz: {
            /** Format: int32 */
            anzahlPersonen?: number;
            event: components["schemas"]["EventResponse"];
            /** Format: int64 */
            id: number;
            partei: components["schemas"]["ParteiKurz"];
            status: components["schemas"]["EinladungStatus"];
        };
        EinladungRequest: {
            /** Format: int32 */
            anzahlPersonen?: number;
            bestaetigungVersendet: boolean;
            buffetBeitrag?: components["schemas"]["BuffetBeitrag"];
            buffetBeitragBeschreibung?: string;
            /** Format: int64 */
            eventId: number;
            hilftAufraumen?: boolean;
            hilftAufstellen?: boolean;
            /** Format: int64 */
            parteiId: number;
            status: components["schemas"]["EinladungStatus"];
        };
        EinladungResponse: {
            /** Format: int32 */
            anzahlPersonen?: number;
            bestaetigungVersendet: boolean;
            buffetBeitrag?: components["schemas"]["BuffetBeitrag"];
            buffetBeitragBeschreibung?: string;
            event: components["schemas"]["EventResponse"];
            hilftAufraumen?: boolean;
            hilftAufstellen?: boolean;
            /** Format: int64 */
            id: number;
            partei: components["schemas"]["ParteiKurz"];
            status: components["schemas"]["EinladungStatus"];
        };
        /** @enum {string} */
        EinladungStatus: "OFFEN" | "ANGEMELDET" | "ABGEMELDET";
        EinladungUpdateRequest: {
            /** Format: int32 */
            anzahlPersonen?: number;
            bestaetigungVersendet: boolean;
            buffetBeitrag?: components["schemas"]["BuffetBeitrag"];
            buffetBeitragBeschreibung?: string;
            hilftAufraumen?: boolean;
            hilftAufstellen?: boolean;
            status: components["schemas"]["EinladungStatus"];
        };
        EventRequest: {
            alternativerStandort?: string;
            /** Format: date */
            datum: string;
            standort: string;
            /** Format: time-local */
            startzeit: string;
            /** Format: time-local */
            zeitAufraumen?: string;
            /** Format: time-local */
            zeitAufstellen?: string;
        };
        EventResponse: {
            alternativerStandort?: string;
            /** Format: date */
            datum: string;
            /** Format: int64 */
            id: number;
            standort: string;
            /** Format: time-local */
            startzeit: string;
            /** Format: time-local */
            zeitAufraumen?: string;
            /** Format: time-local */
            zeitAufstellen?: string;
        };
        KonsumationRequest: {
            /** Format: int32 */
            anzahl: number;
            /** Format: int64 */
            konsumationsangebotId: number;
            /** Format: int64 */
            teilnahmeId: number;
        };
        KonsumationResponse: {
            /** Format: int32 */
            anzahl: number;
            /** Format: int64 */
            id: number;
            konsumationsangebot: components["schemas"]["KonsumationsangebotKurz"];
            teilnahme: components["schemas"]["TeilnahmeKurz"];
        };
        KonsumationsangebotKurz: {
            bezeichnung: string;
            /** Format: int64 */
            id: number;
            preis: number;
        };
        KonsumationsangebotRequest: {
            bezeichnung: string;
            /** Format: int64 */
            eventId: number;
            preis: number;
        };
        KonsumationsangebotResponse: {
            bezeichnung: string;
            event: components["schemas"]["EventResponse"];
            /** Format: int64 */
            id: number;
            preis: number;
        };
        KonsumationUpdateRequest: {
            /** Format: int32 */
            anzahl: number;
        };
        LoginRequest: {
            email: string;
            passwort: string;
        };
        LoginResponse: {
            token: string;
        };
        MahnungRequest: {
            /** Format: int64 */
            abrechnungId: number;
            bemerkung?: string;
            /** Format: date */
            datum: string;
        };
        MahnungResponse: {
            abrechnung: components["schemas"]["AbrechnungKurz"];
            bemerkung?: string;
            /** Format: date */
            datum: string;
            /** Format: int64 */
            id: number;
        };
        ParteiKurz: {
            adresse: string;
            bezeichnung: string;
            /** Format: int64 */
            id: number;
            twintAktiv: boolean;
            twintMobilenummer?: string;
        };
        ParteiRequest: {
            adresse: string;
            bezeichnung: string;
            personenIds?: number[];
            twintAktiv: boolean;
            twintMobilenummer?: string;
        };
        ParteiResponse: {
            adresse: string;
            bezeichnung: string;
            /** Format: int64 */
            id: number;
            personen: components["schemas"]["PersonResponse"][];
            twintAktiv: boolean;
            twintMobilenummer?: string;
        };
        PasswortReset: {
            passwort: string;
        };
        PersonRequest: {
            email?: string;
            mobilenummer?: string;
            name: string;
            telefonnummer?: string;
            vorname: string;
        };
        PersonResponse: {
            email?: string;
            /** Format: int64 */
            id: number;
            mobilenummer?: string;
            name: string;
            telefonnummer?: string;
            vorname: string;
        };
        /** @enum {string} */
        Rolle: "ORGANISATOR" | "PARTEI";
        TeilnahmeBuffetBeitrag: {
            art: components["schemas"]["BuffetBeitrag"];
            beschreibung?: string;
        };
        TeilnahmeKurz: {
            einladung: components["schemas"]["EinladungKurz"];
            /** Format: int64 */
            id: number;
        };
        TeilnahmeRequest: {
            /** Format: int32 */
            anzahlPersonenEffektiv?: number;
            buffetBeitraege?: components["schemas"]["TeilnahmeBuffetBeitrag"][];
            /** Format: int64 */
            einladungId: number;
            hilftAufraumen?: boolean;
            hilftAufstellen?: boolean;
        };
        TeilnahmeResponse: {
            /** Format: int32 */
            anzahlPersonenEffektiv?: number;
            buffetBeitraege: components["schemas"]["TeilnahmeBuffetBeitrag"][];
            einladung: components["schemas"]["EinladungKurz"];
            hilftAufraumen?: boolean;
            hilftAufstellen?: boolean;
            /** Format: int64 */
            id: number;
        };
        TeilnahmeUpdateRequest: {
            /** Format: int32 */
            anzahlPersonenEffektiv?: number;
            buffetBeitraege?: components["schemas"]["TeilnahmeBuffetBeitrag"][];
            hilftAufraumen?: boolean;
            hilftAufstellen?: boolean;
        };
        ZahlungRequest: {
            /** Format: int64 */
            abrechnungId: number;
            betrag: number;
            /** Format: date */
            datum: string;
            zahlungskanal: components["schemas"]["Zahlungskanal"];
        };
        ZahlungResponse: {
            abrechnung: components["schemas"]["AbrechnungKurz"];
            betrag: number;
            /** Format: date */
            datum: string;
            /** Format: int64 */
            id: number;
            zahlungskanal: components["schemas"]["Zahlungskanal"];
        };
        /** @enum {string} */
        Zahlungskanal: "TWINT" | "UEBERWEISUNG" | "BAR";
        /** @enum {string} */
        Zustellungskanal: "TWINT" | "EMAIL" | "PAPIER";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type AbrechnungKurz = components['schemas']['AbrechnungKurz'];
export type AbrechnungRequest = components['schemas']['AbrechnungRequest'];
export type AbrechnungResponse = components['schemas']['AbrechnungResponse'];
export type AbrechnungUpdateRequest = components['schemas']['AbrechnungUpdateRequest'];
export type AllgemeinausgabeRequest = components['schemas']['AllgemeinausgabeRequest'];
export type AllgemeinausgabeResponse = components['schemas']['AllgemeinausgabeResponse'];
export type ApiError = components['schemas']['ApiError'];
export type BenutzerRequest = components['schemas']['BenutzerRequest'];
export type BenutzerResponse = components['schemas']['BenutzerResponse'];
export type BuffetBeitrag = components['schemas']['BuffetBeitrag'];
export type EinladungKurz = components['schemas']['EinladungKurz'];
export type EinladungRequest = components['schemas']['EinladungRequest'];
export type EinladungResponse = components['schemas']['EinladungResponse'];
export type EinladungStatus = components['schemas']['EinladungStatus'];
export type EinladungUpdateRequest = components['schemas']['EinladungUpdateRequest'];
export type EventRequest = components['schemas']['EventRequest'];
export type EventResponse = components['schemas']['EventResponse'];
export type KonsumationRequest = components['schemas']['KonsumationRequest'];
export type KonsumationResponse = components['schemas']['KonsumationResponse'];
export type KonsumationsangebotKurz = components['schemas']['KonsumationsangebotKurz'];
export type KonsumationsangebotRequest = components['schemas']['KonsumationsangebotRequest'];
export type KonsumationsangebotResponse = components['schemas']['KonsumationsangebotResponse'];
export type KonsumationUpdateRequest = components['schemas']['KonsumationUpdateRequest'];
export type LoginRequest = components['schemas']['LoginRequest'];
export type LoginResponse = components['schemas']['LoginResponse'];
export type MahnungRequest = components['schemas']['MahnungRequest'];
export type MahnungResponse = components['schemas']['MahnungResponse'];
export type ParteiKurz = components['schemas']['ParteiKurz'];
export type ParteiRequest = components['schemas']['ParteiRequest'];
export type ParteiResponse = components['schemas']['ParteiResponse'];
export type PasswortReset = components['schemas']['PasswortReset'];
export type PersonRequest = components['schemas']['PersonRequest'];
export type PersonResponse = components['schemas']['PersonResponse'];
export type Rolle = components['schemas']['Rolle'];
export type TeilnahmeBuffetBeitrag = components['schemas']['TeilnahmeBuffetBeitrag'];
export type TeilnahmeKurz = components['schemas']['TeilnahmeKurz'];
export type TeilnahmeRequest = components['schemas']['TeilnahmeRequest'];
export type TeilnahmeResponse = components['schemas']['TeilnahmeResponse'];
export type TeilnahmeUpdateRequest = components['schemas']['TeilnahmeUpdateRequest'];
export type ZahlungRequest = components['schemas']['ZahlungRequest'];
export type ZahlungResponse = components['schemas']['ZahlungResponse'];
export type Zahlungskanal = components['schemas']['Zahlungskanal'];
export type Zustellungskanal = components['schemas']['Zustellungskanal'];
export type $defs = Record<string, never>;
export interface operations {
    findAll_11: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbrechnungResponse"][];
                };
            };
        };
    };
    create_11: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbrechnungRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbrechnungResponse"];
                };
            };
        };
    };
    update_8: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbrechnungUpdateRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbrechnungResponse"];
                };
            };
        };
    };
    delete_8: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll_10: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllgemeinausgabeResponse"][];
                };
            };
        };
    };
    create_10: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllgemeinausgabeRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllgemeinausgabeResponse"];
                };
            };
        };
    };
    update_7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllgemeinausgabeRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AllgemeinausgabeResponse"];
                };
            };
        };
    };
    delete_7: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    findAll_9: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenutzerResponse"][];
                };
            };
        };
    };
    create_9: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BenutzerRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenutzerResponse"];
                };
            };
        };
    };
    delete_11: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    passwortSetzen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswortReset"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BenutzerResponse"];
                };
            };
        };
    };
    findAll_8: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EinladungResponse"][];
                };
            };
        };
    };
    create_8: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EinladungRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EinladungResponse"];
                };
            };
        };
    };
    update_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EinladungUpdateRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EinladungResponse"];
                };
            };
        };
    };
    delete_6: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll_7: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"][];
                };
            };
        };
    };
    create_7: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
        };
    };
    update_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
        };
    };
    delete_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KonsumationResponse"][];
                };
            };
        };
    };
    create_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KonsumationRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KonsumationResponse"];
                };
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KonsumationUpdateRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KonsumationResponse"];
                };
            };
        };
    };
    delete_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KonsumationsangebotResponse"][];
                };
            };
        };
    };
    create_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KonsumationsangebotRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KonsumationsangebotResponse"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KonsumationsangebotRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KonsumationsangebotResponse"];
                };
            };
        };
    };
    delete_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MahnungResponse"][];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MahnungRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MahnungResponse"];
                };
            };
        };
    };
    delete_10: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParteiResponse"][];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParteiRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParteiResponse"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParteiRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParteiResponse"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonResponse"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findAll_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeilnahmeResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeilnahmeRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeilnahmeResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeilnahmeUpdateRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeilnahmeResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    findMeine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeilnahmeResponse"];
                };
            };
        };
    };
    findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZahlungResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZahlungRequest"];
            };
        };
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZahlungResponse"];
                };
            };
        };
    };
    delete_9: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Fehler im einheitlichen Format (ERROR-001) */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
